 
version: "3.8"

services: 
  redis-service:
    image: redis:8.4.0    
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=redispass
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks: 
      - ms_new_boilerplate_network
