version: "3.8"

services:
  rabbitmq-service:
    image: rabbitmq:4-management
    container_name: rabbitmq-service
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - ms_new_boilerplate_network
