version: "3.8"

services:
  app:
    image: app
    container_name: app
    env_file: ../../.env
    build:
      context: ../../
      dockerfile: Dockerfile
      target: build
      args:
        token_packages: ${TOKEN_PACKAGES}
    ports:
      - ${PORT}:${PORT}
    environment:
      DB_CONNECTION_STRING: mongodb://root:example@mongo:27019/?authMechanism=DEFAULT
    networks:
      - ms_new_boilerplate_network
    restart: always
    command: yarn start:dev
    depends_on:
      - mongo-service
